Dockerization
Fenixhack/alfarroba pull request #22
Opened 2018-06-07 16:47 UTC by mcoquet

Added a Dockerfile and a docker-compose.yml so using docker to run the app can be made easier. 

The compose file is geared towards development, but the Dockerfile should work for any enviroment.

2018-06-08 13:24 UTC, semsomi requested changes

2018-06-08 13:46 UTC, mcoquet commented on docker-compose.yml
> +    environment:
Thats fair. I wanted to include some basic env settings , not necessarily all of them, but wasn't sure which were absolutely required to run. 

We could run `npm run config` as part of the build to copy the env file, but then the image would INCLUDE that file in it, meaning its not as readily editable as normal. 

Maybe just not have the ENV vars in this file at all and have the app explicitly complain about it?

That would make it clean and OBVIOUS what is missing?

2018-06-08 13:47 UTC, mcoquet commented on docker-compose.yml
> +    environment:
also, of note, as it is now, if you DO have an env file, it overrides whats set in this one I think

2018-06-09 09:52 UTC, semsomi approved these changes
Awesome! :smiley:

2018-06-09 09:52 UTC, merged